### ISSUE TITLE
spansh integration (usage?) issues

### ISSUE THREAD

**Issue by andyhunne** [alterNERDtive/VoiceAttack-profiles#103]
Firstly, thanks so much for making your VA profiles and associated software available - it makes ED infinitely more enjoyable.

Following the documentation, I am able to target a system with the Galaxy Map, then either from the first tab or the cockpit, have the system plot a route via the "plot neutron route" command.  Voice Attack responds by first prompting me for the jump range, and then by responding with "Plotting Neutron route...X jumps to (target system).  First waypoint (target system).

So in this example, and each time I've attempted to use the integration with spansh, (target system) is always the first waypoint, no matter how many jumps away it is.  

It is my understanding that the expected behaviour is for the Galaxy Map to open with the first waypoint targeted, rather than the destination (target system).

Thanks in advance for any help.

**Comment by alterNERDtive** [comment]
> It is my understanding that the expected behaviour is for the Galaxy Map to open with the first waypoint targeted, rather than the destination (target system).

Yes. It should also tell you the first waypoint as the first waypoint, obviously.

Do you have an actual example with starting and target system?

Also can you add a screenshot of your VoiceAttack log right after starting it?

**Comment by andyhunne** [comment]
In this example, I'm in LHS 448, wanting to jump to Diaguandri.  I searched for Diaguandri on the 2nd tab of the galaxy map, selected it, closed the galaxy map, then used the voice command:

"plot neutron route"

As you can see in the log, this succeeded in the first part, however, still opens the galaxy map with Diaguandri targeted.  I did it twice in this log example as I'd forgotten to focus back on the ED window after manually entering my jump range.

This is consistent behaviour I am seeing over 10 tests in the past 24 hours.  Happy to provide any other info required.

![edSpanshIssue](https://user-images.githubusercontent.com/10094551/111544547-5ab1bb80-87c0-11eb-8148-92dd7a16cef7.PNG)

**Comment by alterNERDtive** [comment]
> I'm in LHS 448, wanting to jump to Diaguandri.

Those are 174.36 ly apart without any neutrons anywhere near. Of course you can’t plot a neutron route :)

Also with your range neutron jumping won’t do much anyway, might even be detrimental.

**Comment by andyhunne** [comment]
Ah, so neutron jumping is different to 'normal' jumping?  I had no idea ;)

Thanks for pointing that out - I guess I've got a bit of reading to do - noob mistake!

**Comment by alterNERDtive** [comment]
> Ah, so neutron jumping is different to 'normal' jumping? I had no idea ;)

Well, yes. [It’s for long range travel](https://spansh.co.uk/plotter/results/A482EDBA-8770-11EB-8199-60DF94EB4526?efficiency=60&from=Sol&range=75&to=Colonia), since neutrons give you a 300% boost to jump range. There are only a handful in the bubble though and diverting to them usually isn’t worth it.

You want to just use the galaxy maps regular route plotting thing.
