### ISSUE TITLE
EDDI quiet mode

### ISSUE THREAD

**Issue by Carl-Ren** [alterNERDtive/VoiceAttack-profiles#107]
When changing EDDI quiet mode setting, voice line reply: Not set disabled.

And setting doesn't change if I call the setting report.

**Comment by Carl-Ren** [comment]
FYI: auto update check setting fully functional

**Comment by Carl-Ren** [comment]
Problem solved, I should pronounce EDDI as eddy.

**Comment by alterNERDtive** [comment]
Uh … what _did_ you pronounce it as? Because no commands should fire for random phrases :D

**Comment by Carl-Ren** [comment]
E D D I  XD

Speak of which, would you mind double-check the key sequence for auto restock function?

I think the condition <select> is in the wrong place and should place before the <rightkey>

**Comment by alterNERDtive** [comment]
> Speak of which, would you mind double-check the key sequence for auto restock function?

I can; but I use that frequently when I do AX to preserve my premium ammo, and it’s been working fine.

**Comment by alterNERDtive** [comment]
> I can; but I use that frequently when I do AX to preserve my premium ammo, and it’s been working fine.

Just for the record, can confirm that it’s still working as intended here.
