### ISSUE TITLE
Horizons Binding compatibility.

### ISSUE THREAD

**Issue by wizardkitty** [alterNERDtive/VoiceAttack-profiles#118]
It seems the program is currently unable to switch between the two bindings. Odyssey works fine but it seems its not changing the binds file to the horizons one in horizons causing issues.

It does say it's "using" the 3.0 in the logs but in reality its using the 4.0 binds in horizons.

I have made sure all bindings are set and that bindEd had them. But its still using the odyssey binds while in horizons.

**Comment by alterNERDtive** [comment]
[Is it doing this?](https://alternerdtive.github.io/bindED/troubleshooting/#horizons-vs-odyssey)
