### ISSUE TITLE
EDDI’s “update available” TTS at VoiceAttack start is cut off.

### ISSUE THREAD

**Issue by alterNERDtive** [alterNERDtive/VoiceAttack-profiles#120]
This is more of an FYI than an actual issue I’m planning on working on.

When my profiles’ `startup` command runs it puts EDDI into quiet mode (by default). That also _cuts off any currently playing TTS_.

I’m not sure how to fix this properly (no, adding a delay is not fixing it properly). Open for suggestions.

**Comment by Tkael** [comment]
Perhaps check the value of `{BOOL:EDDI speaking}` and set quiet mode once the value becomes false?

**Comment by alterNERDtive** [comment]
That was of course to simple for me to think of ;)
