### ISSUE TITLE
Add command to toggle off features such as going to startport services automatically.

### ISSUE THREAD

**Issue by jtwadsworth** [alterNERDtive/VoiceAttack-profiles#133]

**Comment by alterNERDtive** [comment]
“Such as”? Which others did you have in mind? :)

**Comment by jtwadsworth** [comment]
1. Automatic starport services
2. Automatic retracting landing gear
3. Shutting off lights on SRV deployment

Basicallly, anything that is automatically happening could be toggleable with a voice command in case the user does not want those functions automated.

**Comment by alterNERDtive** [comment]
Yuck, I forgot about landing gear / SRV lights. Oh well …

**Comment by alterNERDtive** [comment]
@jtwadsworth I’m not going to push yet another release, but here’s a package with the other two options added https://fuelrats.cloud/s/pZrLZR9W8EtBHgR
