### ISSUE TITLE
EDDI doesn't correctly announce landing pad

### ISSUE THREAD

**Issue by jtwadsworth** [alterNERDtive/VoiceAttack-profiles#134]
EDDI says "Landing pad is at _ as you enter with green lights on your right."

**Comment by alterNERDtive** [comment]
Does this happen in any specific situation, or always?

In any case, this is probably an issue with EDDI itself; all the command does is invoke the `speech` context with `Landing pad report`.

**Comment by jtwadsworth** [comment]
Always. I've not heard it correctly report the location.

**Comment by alterNERDtive** [comment]
Well, you’ll have to ask the EDDI guys about that.
