### ISSUE TITLE
autoRestock always skips over reful it seems

### ISSUE THREAD

**Issue by koshibb** [alterNERDtive/VoiceAttack-profiles#135]
I am unsure if this is a delay issue or what is causing it, but it seems that when entering / landing at a station, the auto restock script executes but it doesn't actually 'click' the refuel option.

**Comment by alterNERDtive** [comment]
Can you record a short video and upload somewhere? Last time I played it worked just fine for me.

The only thing I can think of off the top of my head is server lag; sometimes it takes a few seconds for the refuel/restock/rearm buttons to actually light up and do anything.

**Comment by koshibb** [comment]
Is there a way to update the 'delay' in the actual automated program?

**Comment by alterNERDtive** [comment]
Making delays configurable is on the list™ but I doubt I’ll get around to implementing it; that would still be more for performance reasons than network lag though. So lag is the problem in your case?

**Comment by koshibb** [comment]
I do not know. Ill make a video next time I play.

**Comment by alterNERDtive** [comment]
Have you been able to reproduce and document the issue?

**Comment by alterNERDtive** [comment]
Closed for lack of user input.
