### ISSUE TITLE
have a general VoiceAttack HowTo in the docs

### ISSUE THREAD

**Issue by alterNERDtive** [alterNERDtive/VoiceAttack-profiles#14]
* how to import profiles
* how to include profiles
* how to change commands (e.g. to set configuration variables)
* how to install plugins
* how to install the scripts

**Comment by SweetyVolty** [comment]
just here for asking this. where are we supposed to put the 3 elite script .exe's?

**Comment by alterNERDtive** [comment]
If you use the provide .vax file on the [release page](../releases/latest) they are included.

If not and you haven’t changed anything, `Sounds\scripts` within your VA installation folder.

**Comment by SweetyVolty** [comment]
Ah okay, just bought the voice attack and still trying to figure it out so actually found a nice explanation in the profile's source.zip file. 

btw-1 Your discord links are most likely expired, you should create a permanent link like this; 
 https://imgur.com/a/ABrrj20

btw-2 I'm receiving this error and found no way to add this startup item to general ED profile :( I'm using the .vax package; 
UNABLE TO EXECUTE COMMAND, 'SpanshAttack.startup' (by name). COMMAND NOT AVAILABLE.

**Comment by alterNERDtive** [comment]
> btw-1 Your discord links are most likely expired, you should create a permanent link like this;
> https://imgur.com/a/ABrrj20

Thanks, I’ll have to look into that. Use this one in the mean time: https://discord.gg/fgZQRmG

> btw-2 I'm receiving this error and found no way to add this startup item to general ED profile :( I'm using the .vax package;
> UNABLE TO EXECUTE COMMAND, 'SpanshAttack.startup' (by name). COMMAND NOT AVAILABLE.

If you have imported everything and not deselected anything from the file, it should have imported the SpanshAttack profile and shouldn’t run into that problem.

If you have chosen to import only specific stuff, just ignore the error. Should still work fine otherwise.

**Comment by alterNERDtive** [comment]
This is partly included in the new documentation and partly obsolete, me thinks.
