### ISSUE TITLE
Cannot autoenter Station Services after docking

### ISSUE THREAD

**Issue by ACyprus** [alterNERDtive/VoiceAttack-profiles#142]
Possibly related to #135 ?

Again, this worked reliably in 3.0 but I've had problems with it since updating to the current version profile.

Initially, only "auto hangar" and "auto station services" settings were enabled. Focus would move to the "go to hangar" button, select it but remain there.

I then switched to testing with everything enabled:

![image](https://user-images.githubusercontent.com/9026246/170786545-4e8682e3-b060-4521-b2b6-1e82b488c09e.png)

I increased the pause delays in `EliteAttack.EDDI Docked` so I could see clearly what is happening.

Weird af because the actions I see on screen do not resemble the profile command.

On docking, the command clicks each button in the row, gets as far as "go to hangar", then seems to move horizontally through the button row again TWICE from left to right, finally coming to stop on the hangar button - but never moves down to station services.

Sounds crazy, right?

I'm unable to record this but can stream on Discord if that helps.

In case this is useful:

[bindED-missingBings.txt](https://github.com/alterNERDtive/VoiceAttack-profiles/files/8789654/bindED-missingBings.txt)

(I don't see `edUI_Down` in there)

**Comment by ACyprus** [comment]
I managed to record this for you, apologies for the shitty resolution.

[Here's the clip](https://drive.google.com/file/d/1YqqXkfzaPpjua_L8A_whpEp8-agb_Fva/view?usp=sharing), around 12mb.

I'm using the same settings as above so it seems to have skipped some buttons in the first row too oddly.

**Comment by alterNERDtive** [comment]
Well, I made a typo … the option is defined as `autoStationService` by accident, and (correctly) referred to as `EliteAttack.autoStationServices#` (with an `s` at the end) in the profile.

**Comment by alterNERDtive** [comment]
> On docking, the command clicks each button in the row, gets as far as "go to hangar", then seems to move horizontally through the button row again TWICE from left to right, finally coming to stop on the hangar button - but never moves down to station services.

This one I can’t reproduce though oO
