### ISSUE TITLE
Request StreamAttack - Current Game Date/Time to Text File

### ISSUE THREAD

**Issue by ArsenCross** [alterNERDtive/VoiceAttack-profiles#156]
Would be nice if the current time in game, including the year was output to a text file for overlay.

**Comment by alterNERDtive** [comment]
Honestly no idea if there’s a way to get that easily. Otherwise it’s a job for a plugin, just put out UTC time + add some odd years.

**Comment by alterNERDtive** [comment]
I kind of don’t like constantly writing the time to a file. IMO the “correct” way to include a clock in OBS would be either a plugin (a bit overkill) or a simple HTML document with an embedded JS clock. Similar to what <https://obsproject.com/forum/resources/clock.566/> does (bonus points for XKCDs in the demonstration video. Game time would just be UTC.

Now I _could_ ship that with StreamAttack, but IMO it’s a bit out of scope.
