### ISSUE TITLE
Bandwidth usage from voiceattack

### ISSUE THREAD

**Issue by Robbob1er** [alterNERDtive/VoiceAttack-profiles#164]
Hi, sorry if it is adresssed elseware, I couldn<t find anything related to my problem. I am trying to get an idea of how much bandwidth and Go I need from my internet provider. For that I looked at the network setting of windows 10 and there, you can get data usage of all your apps. And suprise! Voiceattack used nearly 20 Go in the las month!
If I let run VoiceAttack with this profile of course : alternerdtive-base, spanshattack, and Elite attack., And not playing Elite it still takes data on the network.

Could the info dowloaded for EDDI and EDMC be that big?

What could be the problem?

I am on windows 10 with VoiceAttack 1.10.3 from Steam and the latest profile from here.

**Comment by alterNERDtive** [comment]
> Could the info dowloaded for EDDI and EDMC be that big?

Not really, no. Unless you visited half the galaxy. Or maybe that traffic thing is broken, no idea.

Do you have any other plugins installed?

Also, are you on mobile internet or something? Having capped data is … horrible. Like, this is my traffic for the last months: 
![image](https://user-images.githubusercontent.com/53827887/226092589-3e453a0c-fc19-42b9-a086-b7fed114e859.png)

**Comment by Robbob1er** [comment]
HI, I only have yours, I think! I will do a fresh install. I remember that I tried a few other helpers so maybe some stuff was left behind.  I don<t have anywhere near as much usage then you I get around with 100 GiB a mounth.

**Comment by alterNERDtive** [comment]
You could run more diagnostics with e.g. Wireshark and see if you can find out more. I don’t even know if that windows traffic thing even works properly or not.

**Comment by Robbob1er** [comment]
Hi, I fanally came around to do some more tests. I don't have have the knowledge to get all the info but what I found is that something in voice attack, while running the profile, is making connection with api.rollbar.com In a few minutes of usage it alreayd tops to 600 MB just for that site. I'll try to run the profile without add ons like spanshattack and elite attack and just voice attack with bare minimum.

**Comment by alterNERDtive** [comment]
That is definitely not me / my stuff. Apparently EDDI uses rollbar though https://github.com/EDCD/EDDI/search?q=rollbar and also apparently it can be disabled via config file. I suggest you try that and/or file an issue with them.

**Comment by Robbob1er** [comment]
I tried EDDI alone and don<t get that usage of bandwidth. Maybe EDDI AND VoiceAttack does ? I'll try the config of eddi but what could it send? it is 1 GB now! :-(

**Comment by Robbob1er** [comment]
Great it worked! It was the telemetry from EDDI. It seems to be for crashes and debug.
Thanks a lot for all the help.
