### ISSUE TITLE
RatAttack profile not triggering RatAttack.announceCaseDetails

### ISSUE THREAD

**Issue by sparker3d** [alterNERDtive/VoiceAttack-profiles#50]
I have the voice attack profile installed, and have the scrip in AdiIRC.

The scrip looks like this:

> on *:TEXT:RATSIGNAL - CMDR*(??_SIGNAL):#fuelrats:{
  	/mkdir C:\users\Parker\appdata\roaming\RatAttack\
  	/handleratsignal $1-
}
alias handleratsignal {
  	if ( $exists(C:\users\Parker\appdata\roaming\RatAttack\ratsignal.pipe) ) {
    		/sleep 1 /handleratsignal $1-
    	}
    	else {
      		/write C:\users\Parker\appdata\roaming\RatAttack\ratsignal.pipe $1-
      		if ( $away ) {
        			/run -h "C:\Program Files (x86)\VoiceAttack\VoiceAttack.exe" -nofocus -command "RatAttack.getInfoFromRatSignal"
        		}
        		else {
          			/run -h "C:\Program Files (x86)\VoiceAttack\VoiceAttack.exe" -nofocus -command "RatAttack.announceCaseFromRatSignal"
        	    }
        	}
      }

I cannot figure out why it is not triggering the commands within voiceattack. The ratsignal.pipe file gets generated perfectly, and read when voiceattack first opens, but it will not trigger the commands for some reason.

**Comment by alterNERDtive** [comment]
Are you running VoiceAttack as admin? You shouldn’t.

If you have to for some reason, you need to run your IRC client as admin, too. Otherwise it cannot invoke VoiceAttack commands.

**Comment by alterNERDtive** [comment]
(Added a note about it to the docs because it will probably come up again <.<)

**Comment by sparker3d** [comment]
After running AdiIRC and re configuring it because it changes your settings when you run as admin? It worked as intended
