### ISSUE TITLE
Additional Command Words for `what’s left to map`

### ISSUE THREAD

**Issue by F3Speech** [alterNERDtive/VoiceAttack-profiles#54]
[whats;what is] left to [map;be mapped] - Could you add **bodies** and **scan** to the initial command [whats;what is;**bodies**] left to [map;be mapped;**scan**]

**Comment by alterNERDtive** [comment]
Bodies: coming right up.

Scan: IDK, that might be confusing since a “scan” would be FSS while a “map” is clearly DSS. On the other hand there isn’t any reason to have a list of things that still need FSSing, and you can’t even properly populate it in a “fresh” system …

**Comment by alterNERDtive** [comment]
From Discord:

```
[16:17] A.Cyprus: I call that using [report;] mapping candidates
```

**Comment by F3Speech** [comment]
I started saying scan as thats what EDDI uses when reporting how many, or lying to you when wheres actually no bodies :)
