### ISSUE TITLE
Add command `[deactivate;disengage;activate;engage] supercruise assist`

### ISSUE THREAD

**Issue by SiIason** [alterNERDtive/VoiceAttack-profiles#56]
![image](https://user-images.githubusercontent.com/2955537/90168591-35c21980-dd95-11ea-85cb-62db31f41d50.png)

Requires body to be selected in external panel (as if you've just selected it manually as a target).
So potential for unwanted outcome if used inappropriately.

**Comment by alterNERDtive** [comment]
I’m not sure about this one; I don’t know how useful it would actually be considering a) you can just throttle up / down to override SC Assist and b) (especially for carriers, have to do more testing for other stuff) the game now likes to randomly select a different target once you go into SC than you had selected beforehand (e.g. after undocking).

**Comment by F3Speech** [comment]
I use this when mapping planets, it's a quality of life change nothing more really (saves a few seconds in the menus).

I'm very open to the suggestion this steps over the line of whats reliable enough to include, but it's here because I use it 👍 
Also, maybe I need to learn to map planets better... lol

**Comment by alterNERDtive** [comment]
I guess the main question is “depending on what might randomly be selected in the nav panel, what might this accidentally do (with and without sc assist installed)?”.

**Comment by alterNERDtive** [comment]
Given that there is no way to know which target is selected in the nav panel (nor one to select the correct one automatically) I’m going to not look into ways how to partially implement this.

I don’t see the benefits in having a command that does `select` → `right` → `select` for me, and that i first have to open the nav panel and select (or at least hover) the right target for.
