### ISSUE TITLE
Limit execution of a websearch/query to one execution at a time

### ISSUE THREAD

**Issue by F3Speech** [alterNERDtive/VoiceAttack-profiles#59]
![image](https://user-images.githubusercontent.com/2955537/90172161-7ff9c980-dd9a-11ea-847b-a610c086b981.png)

Due to the time taken for some EDDI searchs to run (ie. the related website processing time), its currently possible to think a command hasn't happened or has failed. You then ask the command again (and again...) only to find you then get 3 lots of tts results and 3 lots of possible key/mouse actions... A quick "still running" tts or similar while blocking the second execution would be helpful.

**Comment by alterNERDtive** [comment]
You could say this one slipped the net when I limited certain commands to not execute when they are already running since this is a command, then waiting for an event. Should be simple to fix though.

**Comment by alterNERDtive** [comment]
I’ve also started adding more TTS prompts instead of just a `beep` to commands that might not respond instantaneously, this one is an obvious case for that.

**Comment by alterNERDtive** [comment]
Hmm … so there is no way (at least none I know of) to stop EDDI searching for something once you’ve kicked it off. So … if I e.g. mistakenly start a search for a raw trader, then realize I actually wanted manufactured; is it better to be blocked off until the first, wrong search is done, or to be able to kick off the new one immediately?

Currently I can’t think of a way to be able to do the latter if I limit it to one concurrent search. OTOH allowing it would mean that 2 search results might come in at the same time, leading to fun race conditions with command handling.

I could limit the `EliteDangerous.EDDI Route details` command to one execution at a time, but that would (probably?) mean that the first result might block any coming after.

/incoherent string of thoughts

**Comment by F3Speech** [comment]
In my head I saw the answer as setting a variable generated/set from the <type> and clearing that bool after execution chain finish. Then if that type is called again you get nothing (while waiting) but would allow others types to pass once (but their <type> bool would independently stop those from multiple execution); rather than locking the whole va/eddi command to single execution.

**Comment by alterNERDtive** [comment]
In an ideal world you would only have 1 instance of _any_ search running. You don’t want several searches to finish after each other, trying to plot to different things each time.

Implementing that is fairly easy; the question is what to do then with an accidental search that you want to “override” so to speak (to be clear, that is currently _not possible_ either).

**Comment by F3Speech** [comment]
I've got some ideas on this but without looking at the plugin return I don't know how viable they are. Will have a play and feedback any ideas.
