### ISSUE TITLE
Make EliteDangerous.announceR2RMappingCandidates independent of [System visits] check in EliteDangerous.EDDI Jumped

### ISSUE THREAD

**Issue by F3Speech** [alterNERDtive/VoiceAttack-profiles#61]
Noticed tonight some systems not scanning/honking, and its because I've been via then a couple of times.
This is fine, makes sense but also noticed I wasn't been told of R2R candidates that I previously skipped.

Think if you have R2R on in the settings then this function/check should fire for every system known about or not.

NB: I haven't checked if this is also the case for the function matching spanch and edsm data (as that would also be handy having separate; regardless of honk imo)

**Comment by alterNERDtive** [comment]
Yeah, that should belong into `Jumped` not `Discovery scan`. Good catch.

> NB: I haven't checked if this is also the case for the function matching spanch and edsm data

Data is requested on `Jumped` and then we just hope that it has returned something (or errored out) by the time the `Discovery scan` hits :shrug:

… I have run into a bunch of instances lately with EDSM timing out / taking very long to answer and bodies being checked against last system’s count :-/ (In fact, lemme fix that real quick …)

**Comment by alterNERDtive** [comment]
Caveat: moving this to `Jumped` will probably make #64 worse.
