### ISSUE TITLE
Outdated info in Shutdown 

### ISSUE THREAD

**Issue by Catreina** [alterNERDtive/VoiceAttack-profiles#74]
Per alterNERDtive - issue filed for outdated information concerning IRC nick changes and possible impersonation

https://github.com/alterNERDtive/VoiceAttack-profiles/blob/release/docs/EliteDangerous.md#shutdown

**Comment by alterNERDtive** [comment]
https://github.com/alterNERDtive/VoiceAttack-profiles/blob/release/docs/EliteDangerous.md#commander-loading ← that one, too
