### ISSUE TITLE
EliteDangerous.readBindings throwing "Unable to invoke plugin - plugin not available"

### ISSUE THREAD

**Issue by DieFinsternis** [alterNERDtive/VoiceAttack-profiles#75]
Imported the vax file. 
Created a new profile "MyEliteProfile", 
imported the EliteDangerous profile, 
ran EliteDangerous.startup on load. 
The same happens when loading into the EliteDangerous profile directy.

No change on importing all profiles. I do currently not plan to use any profile but the EliteDangerous one, but for trouble shooting I also got the NeutronRouter. Also tried with bindED v2.0 since it fit release dates better.

I'm at a loss, I was under the assumption I followed your install guide correctly. After re-reading it I still can't see the issue. VA isn't helping with not even telling me what that "unable to access" line was supposed to do beforehand.
Any idea?

Log:

> 10:24:53.694 UNABLE TO INVOKE PLUGIN. PLUGIN NOT AVAILABLE.
> 10:24:53.539 UNABLE TO EXECUTE COMMAND, 'StreamAttack.startup' (by name). COMMAND NOT AVAILABLE.
> 10:24:53.535 UNABLE TO EXECUTE COMMAND, 'SpanshAttack.startup' (by name). COMMAND NOT AVAILABLE.
> 10:24:53.531 UNABLE TO EXECUTE COMMAND, 'RatAttack.startup' (by name). COMMAND NOT AVAILABLE.
> 10:24:53.506 Profile startup : 'startup'
> 10:24:53.383 Profile changed to MyEliteProfile

After adding some debug log lines I figured it is the EliteDangerous.readBindings function. Which looks like this on my end:
```
=== _correct_ bindings pl0x
Set text [~bindingsDir] to '%localappdata%\Frontier Developments\Elite Dangerous\Options\Bindings\'
Set text [~bindingsProfile] to [{TXT:~bindingsDir}StartPreset.start]
Set text [~bindingsFile] to '{TXT:~bindingsDir}{TXT:~bindingsProfile}.3.0.binds'
Set integer [~bindingsFileExists] value to the converted value of {STATE_FILEEXISTS:~bindingsFile}
Begin Integer Compare : [~bindingsFileExists] Equals 0
    Set text [~bindingsFile] to '{TXT:~bindingsDir}{TXT:~bindingsProfile}.binds'
End Condition
Execute command, 'Logging.log.blue' - passing values
UNABLE TO ACCESS PLUGIN - PLUGIN NOT AVAILABLE
```
Voice Attack Version:
. 1.8.7 - Steam

Plugins as in VoiceAttack: 
. bindED Plugin v3.0-alterNERDtive (v4 bindEDplugin.dll)
. EDDI 3.7.1 (v4 EddiVoiceAttackResponder.dll)
. Neutron Router - v0.1.0+ (v4 EDNeutronRouter.dll)

Profiles: 
. alterNERDtive-voiceattack-profiles.vax Release 3.1.3

Oh, and Elite Dangerous: Horizons, afaia up to date, from the Epic Store.

**Comment by alterNERDtive** [comment]
> 10:24:53.694 UNABLE TO INVOKE PLUGIN. PLUGIN NOT AVAILABLE.

That is not an issue. Everything is still working correctly.

It happens because I stopped linking the old bindED plugin and instead linked to my fork of it. It no longer needs to be invoked to work, it just does its thing. Maybe I should do _another_ intermediate release just to get rid of that error, though.

> 10:24:53.539 UNABLE TO EXECUTE COMMAND, 'StreamAttack.startup' (by name). COMMAND NOT AVAILABLE.
> 10:24:53.535 UNABLE TO EXECUTE COMMAND, 'SpanshAttack.startup' (by name). COMMAND NOT AVAILABLE.
> 10:24:53.531 UNABLE TO EXECUTE COMMAND, 'RatAttack.startup' (by name). COMMAND NOT AVAILABLE.

These are because you haven’t included these 3 profiles; that might be on purpose, though :)

**Comment by alterNERDtive** [comment]
For reference: https://github.com/alterNERDtive/bindED#migrating-from-the-old-plugin

**Comment by alterNERDtive** [comment]
Hmm. After giving it some thought I should probably just go back to linking to the old one in the README for now. Because if I remove the plugin invocation / change it to the new plugin, that means users that haven’t upgraded their bindED plugin will see their keybinds break.

**Comment by alterNERDtive** [comment]
Also if you want to keep the new version of bindED (which I would recommend) but still get rid of that message because it triggers you (as it would me), go ahead and delete/disable the last action in `EliteDangerous.startup`:

![image](https://user-images.githubusercontent.com/53827887/100540371-5b3c3b80-323d-11eb-8148-9a19da86e7cd.png)

**Comment by DieFinsternis** [comment]
Ah, I see.
I thought it was relevant, since my ingame commands would not fire, yet the outside commands (like open that website) do. Due to your answer I started fiddling around with it again, among other things changing language engine, and it turns out it works after all.

But I'm also new to VoiceAttack, so I didn't realize yet that the program just does not understand me. Maybe my accent is too strong or something. Since one apparently also can only train the system language, I'll probably just have to translate the commands to my system language, but that is my own issue.

Thank you for clearing that up and sorry for essentially troubling you with my own issues.

**Comment by alterNERDtive** [comment]
> my ingame commands would not fire

The first step if you run into this is looking at the VA log to narrow down the issue. As you’ve said in this case it was the recognition; if it complains about variable key presses not being set, you have missing key binds in Elite.

> one apparently also can only train the system language

Yeah I’ve heard that recently. Workaround is changing system language to your target language, running the training a couple times, then switching back to whatever you had before.

Also you might want to check if UK or US speech recognition works better for you. Apart from that there’s also information IIRC on the VA website (and/or in their manual) on how to improve recognition.
