### ISSUE TITLE
Filter / hide `plugin command: …` log spam

### ISSUE THREAD

**Issue by alterNERDtive** [alterNERDtive/VoiceAttack-profiles#77]
So apparently you can add an “Ignore an unrecognized word or phrase” action to a command and that will make it not log when it’s run through a plugin. So I’m going to apply that to some thing …

* definitely the loading/saving a variable from/to the profile commands, they are spammy
* probably in some way to the EDDI event commands; either hiding the actual `((EDDI <event>))` one _or_ the individual profiles’ commands

**Comment by Catreina** [comment]
the action can evidently be anywhere in the VA command to stop the output, but to be safe I had it as the first action in the test command I was using. All of the commands that followed were still executed without issue.
