### ISSUE TITLE
alterNERDtive-base is missing 

### ISSUE THREAD

**Issue by suryakumaran11** [alterNERDtive/VoiceAttack-profiles#91]
alterNERDtive-base is no longer available while installing 

only “EliteDangerous”, “RatAttack”, “SpanshAttack”,“StreamAttack” is available . Am I doing something wrong or is it a bug?

**Comment by alterNERDtive** [comment]
Nah, you’re just looking at the docs for 4.0 that isn’t out yet :)

**Comment by alterNERDtive** [comment]
(But unfortunately I’ve already removed the disclaimer because it should have been out.)

**Comment by suryakumaran11** [comment]
ty for the quick reply .  What is thw quick fix to get it running ? 

Choose “Execute by name (Advanced)” and enter ((alterNERDtive-base.startup)).   this wont work

**Comment by alterNERDtive** [comment]
Wait half an hour or so, download 4.0. Currently prepping the release.

**Comment by suryakumaran11** [comment]
ty vm

**Comment by alterNERDtive** [comment]
Please let me know if you run into any issues, since I rewrote a lot of stuff and the entire documentation from scratch :)
